name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests and linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: '4.0'

      - name: Install dependencies
        run: yarn install

      - name: Install Sapling
        run: npx npm-install-peers

      - name: Run linter
        run: npm run lint

      - name: Run test
        run: npm run test:report

      - name: Report coverage
        run: npm run test:send